FREQUENCY_AMALGAMATE = 15
FREQUENCY_BALANCE = 15
FREQUENCY_DEPOSIT_CHECKING = 15
FREQUENCY_SEND_PAYMENT = 25
FREQUENCY_TRANSACT_SAVINGS = 15
FREQUENCY_WRITE_CHECK = 15

TABLENAME_ACCOUNTS = "ACCOUNTS"
TABLENAME_SAVINGS = "SAVINGS"
TABLENAME_CHECKING = "CHECKING"

BATCH_SIZE = 5000
NUM_ACCOUNTS = 1000000

HOTSPOT_USE_FIXED_SIZE = False
HOTSPOT_PERCENTAGE = 25.0
HOTSPOT_FIXED_SIZE = 100

MIN_BALANCE = 10000
MAX_BALANCE = 50000
